SELECT * FROM ejercicio5b.empleados;
select apellido from empleados;
select distinct apellido from empleados;
select emplaedo_id,cuil_cuit,nombre,apellido,departamento,estado from empleados;
select nombre,apellido from empleados;
select cuil_cuit from empleados;
select concat(nombre,' ',apellido) as nombre_apellido from empleados;
select concat(UPPER(nombre),' ', UPPER(apellido)) as nombre_apellido from empleados;
select concat(LOWER(nombre),' ', LOWER(apellido)) as nombre_apellido from empleados;
SELECT * FROM ejercicio5b.departamentos;
select nombre,presupuesto from departamentos order by presupuesto ASC; 
select nombre from departamentos order by nombre ASC;
select nombre from departamentos order by nombre DESC;
SELECT * FROM ejercicio5b.empleados;
select apellido,nombre from empleados order by nombre ASC;
select * from departamentos;
select nombre,presupuesto from departamentos order by presupuesto desc limit 3;
select nombre,presupuesto from departamentos order by presupuesto asc limit 3;
select nombre,presupuesto from departamentos where presupuesto >= 150000;
select nombre,presupuesto from departamentos where presupuesto >= 100000 and presupuesto <=200000;
select nombre,presupuesto from departamentos where presupuesto between 100000 and 200000;
select * from empleados;
select empleados.nombre as Nombre, empleados.apellido as Apellidos, departamentos.nombre as Nombre_Depa from empleados inner join departamentos on empleados.departamento = departamentos.departamento_id;
select empleados.nombre as Nombre, empleados.apellido as Apellidos, departamentos.nombre as Nombre_Depa from empleados inner join departamentos on empleados.departamento = departamentos.departamento_id order by Nombre_depa ASC, empleados.apellido, empleados.nombre;
-- SELECT departamentos.departamento_id, departamentos.nombre FROM departamentos AS ID_NOMBRE INNER JOIN empleados AS Empleados_activos ON departamentos.departamento_id = empleados.departamento_id GROUP BY departamentos.departamento_id, departamentos.nombre;
select departamentos.nombre from empleados inner join departamentos on empleados.departamento = departamentos.departamento_id where empleados.cuil_cuit = "27-38382980-3";
SELECT empleados.nombre FROM empleados AS Nombrecitos INNER JOIN departamentos AS Depa_nombre ON departamentos.departamento_id = departamentos.departamento_id WHERE empleados.nombre = 'Pepe' AND empleados.apellido = 'Ruiz';
Select empleados.*, departamentos.nombre from empleados inner join departamentos on empleados.departamento = departamentos.departamento_id and departamentos.nombre = "I+D" order by empleados.nombre, apellido;
Select empleados.*, departamentos.nombre from empleados inner join departamentos on empleados.departamento = departamentos.departamento_id and departamentos.nombre = "Sistemas" order by empleados.nombre, apellido;

